<?php

/* 
 * This file will contain the default configurable options.
 * The aim of this is to reduce the number of issues that occur after updating when a new config option is added
 * 
 * WARNING: Do not edit this file.  You should instead modify the values in your config.php file.
 */ 

// Debug Mode.  Boolean.
$config['debug'] = TRUE;

// Enable log file.  The log file will contain all data that is normally output when running in Daemon mode.  Boolean.
$config['log'] = TRUE;

// Enable cron mode.  Cron mode will only run once and then die.  Boolean.
$config['cron'] = FALSE;

?>